
# Optimal values for Gowalla dataset: dataset gowalla --regs [1e-5] --embed_size 64 --layer_size [64,64,64] --lr 0.0001 --save_flag 1 
#--pretrain 0 --batch_size 1024 --epoch 400 --verbose 1 --node_dropout [0.1] --mess_dropout [0.1,0.1,0.1]

batch_size: 1024
loss_type: 'BPR'
init_method: 'default'
optimizer: 'default'
early_stop: False
factors: 64
node_dropout: 0.1
mess_dropout: 0.1
lr: 0.0001
reg_1: 0.0001
reg_2: 0.0001
epochs: 400
hidden_size_list: ~

# optimal values for Amazon-book dataset python NGCF.py --dataset amazon-book --regs [1e-5] --embed_size 64 --layer_size [64,64,64] --lr 0.0005 
# --save_flag 1 --pretrain 0 --batch_size 1024 --epoch 200 --verbose 50 --node_dropout [0.1] --mess_dropout [0.1,0.1,0.1]
#batch_size: 1024
#loss_type: 'BPR'
#init_method: 'default'
#optimizer: 'default'
#early_stop: False
#factors: 64
#node_dropout: 0.1
#mess_dropout: 0.1
#lr: 0.0005
#reg_1: 0.0001
#reg_2: 0.0001
#epochs: 200
#hidden_size_list: ~