experiment:
  dataset: amazon-book_ngcf
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    test_path: ../data/{0}/test.tsv
  binarize: True
  top_k: 50
  evaluation:
    cutoffs: [5, 10, 20, 30, 40, 50]
    simple_metrics: [nDCG, MAP, MRR, Precision, Recall,F1,HR]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    NGCF:
      meta:
        save_recs: True
      lr: 0.0001
      epochs: 200
      batch_size: 1024
      factors: 64
      l_w: 0.00001
      weight_size: (64,)
      node_dropout: (0.1,)
      message_dropout: (0.1,)
      n_fold: 1
      meta:
        verbose: True
        save_recs: True
# python NGCF.py --dataset amazon-book --regs [1e-5] --embed_size 64 --layer_size [64,64,64] 
#--lr 0.0005 --save_flag 1 --pretrain 0 
#--batch_size 1024 --epoch 200 --verbose 50 --node_dropout [0.1] --mess_dropout [0.1,0.1,0.1]
    